const { request } = require("../../utils/api");
const CURRENCIES = ["CNY", "USD", "EUR", "GBP", "HKD"];
const TRADE_TERMS = ["未指定", "EXW", "FOB", "FCA", "CFR", "CIF", "DAP", "DDP"];
function futureDate(days) { const d = new Date(Date.now() + days * 86400000); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function line() { return { key: `${Date.now()}-${Math.random()}`, name: "", specification: "", unit: "PCS", quantity: "", salesUnitPrice: "", unitNetWeightKg: "", supplierIndex: -1, supplierId: "", purchaseCurrency: "CNY", purchaseUnitPrice: "", remark: "" }; }
Page({
  data: { id: "", revision: 0, loading: true, saving: false, error: "", customers: [], customerNames: [], customerIndex: -1, entities: [], entityNames: [], entityIndex: -1, suppliers: [], supplierNames: [], currencies: CURRENCIES, currencyIndex: 1, tradeTerms: TRADE_TERMS, tradeTermIndex: 0, form: { customerId: "", businessEntityId: "", currency: "USD", tradeTerm: "", paymentTerm: "", customerOrderNo: "", requestedDeliveryDate: futureDate(30), remark: "" }, items: [line()] },
  onLoad(options) { this.setData({ id: options.id || "" }); this.load(); },
  async load() { try { const requests = [request({ url: "/api/customers" }), request({ url: "/api/business-entities" }), request({ url: "/api/suppliers/available" })]; if (this.data.id) requests.push(request({ url: `/api/sales-executions/${encodeURIComponent(this.data.id)}` })); const [c, e, s, detail] = await Promise.all(requests), customers = c.customers || [], entities = (e.entities || []).filter((x) => x.status !== "停用"), suppliers = (s.suppliers || []).filter((x) => x.supplierType === "产品供应商" || x.allowFactoryDocumentUpload); let entityIndex = entities.length ? Math.max(0, entities.findIndex((x) => x.isDefault)) : -1; const patch = { customers, customerNames: customers.map((x) => x.displayName || x.shortName || x.name), entities, entityNames: entities.map((x) => x.displayName || x.shortName || x.name), entityIndex, "form.businessEntityId": entities[entityIndex] && entities[entityIndex].id || "", suppliers, supplierNames: suppliers.map((x) => x.supplierName || x.name) }; if (detail) { const row = detail.execution || detail.data, allocations = []; (row.purchaseOrders || []).forEach((po) => (po.items || []).forEach((x) => allocations.push({ ...x, supplierId: po.supplierId }))); const customerIndex = customers.findIndex((x) => x.id === row.customerId); entityIndex = entities.findIndex((x) => x.id === row.businessEntityId); patch.customerIndex = customerIndex; patch.entityIndex = entityIndex; patch.revision = row.revision; patch.currencyIndex = Math.max(0, CURRENCIES.indexOf(row.currency)); patch.tradeTermIndex = Math.max(0, TRADE_TERMS.indexOf(row.tradeTerm || "未指定")); patch.form = { customerId: row.customerId, businessEntityId: row.businessEntityId, currency: row.currency, tradeTerm: row.tradeTerm || "", paymentTerm: row.paymentTerm || "", customerOrderNo: row.customerOrderNo || "", requestedDeliveryDate: row.requestedDeliveryDate || futureDate(30), remark: row.remark || "" }; patch.items = (row.items || []).map((x, index) => { const allocation = allocations.find((a) => a.executionItemId === x.id || a.salesExecutionItemId === x.id) || {}; const supplierIndex = suppliers.findIndex((supplier) => supplier.id === allocation.supplierId); return { key: x.id || `${index}`, name: x.productNameSnapshot || x.name || "", specification: x.specificationSnapshot || x.specification || "", unit: x.unit || "PCS", quantity: String(x.quantity || ""), salesUnitPrice: String(x.salesUnitPrice || ""), unitNetWeightKg: String(x.unitNetWeightKg || ""), supplierIndex, supplierId: allocation.supplierId || "", purchaseCurrency: allocation.purchaseCurrency || "CNY", purchaseUnitPrice: String(allocation.purchaseUnitPrice || ""), remark: x.remark || "" }; }); } this.setData(patch); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  chooseCustomer(e) { const customerIndex = Number(e.detail.value), customer = this.data.customers[customerIndex], currency = customer.defaultCurrency || this.data.form.currency; this.setData({ customerIndex, "form.customerId": customer.id, "form.currency": currency, currencyIndex: Math.max(0, CURRENCIES.indexOf(currency)) }); },
  chooseEntity(e) { const entityIndex = Number(e.detail.value); this.setData({ entityIndex, "form.businessEntityId": this.data.entities[entityIndex].id }); },
  chooseCurrency(e) { const currencyIndex = Number(e.detail.value); this.setData({ currencyIndex, "form.currency": CURRENCIES[currencyIndex] }); },
  chooseTradeTerm(e) { const tradeTermIndex = Number(e.detail.value); this.setData({ tradeTermIndex, "form.tradeTerm": tradeTermIndex ? TRADE_TERMS[tradeTermIndex] : "" }); },
  chooseSupplier(e) { const index = Number(e.currentTarget.dataset.index), supplierIndex = Number(e.detail.value); this.setData({ [`items[${index}].supplierIndex`]: supplierIndex, [`items[${index}].supplierId`]: this.data.suppliers[supplierIndex].id }); },
  onFormInput(e) { this.setData({ [`form.${e.currentTarget.dataset.field}`]: e.detail.value }); }, onItemInput(e) { this.setData({ [`items[${Number(e.currentTarget.dataset.index)}].${e.currentTarget.dataset.field}`]: e.detail.value }); },
  addItem() { this.setData({ items: [...this.data.items, line()] }); }, removeItem(e) { if (this.data.items.length > 1) this.setData({ items: this.data.items.filter((_, i) => i !== Number(e.currentTarget.dataset.index)) }); },
  validate() { const f = this.data.form; if (!f.customerId) return "请选择客户"; if (!f.businessEntityId) return "请选择业务主体"; if (!f.customerOrderNo.trim()) return "请填写客户订单号"; if (!f.requestedDeliveryDate) return "请选择客户要求交货日期"; for (let i = 0; i < this.data.items.length; i += 1) { const x = this.data.items[i]; if (!x.name.trim()) return `第 ${i + 1} 行请填写产品描述`; if (!(Number(x.quantity) > 0)) return `第 ${i + 1} 行销售数量必须大于 0`; if (x.salesUnitPrice === "" || Number(x.salesUnitPrice) < 0) return `第 ${i + 1} 行请填写有效销售单价`; if (!x.supplierId) return `第 ${i + 1} 行请选择工厂`; } return ""; },
  async submit() { if (this.data.saving) return; const message = this.validate(); if (message) return this.setData({ error: message }); this.setData({ saving: true, error: "" }); try { const f = this.data.form; const items = this.data.items.map((x) => ({ name: x.name.trim(), specification: x.specification.trim(), unit: x.unit.trim(), quantity: x.quantity.trim(), salesUnitPrice: x.salesUnitPrice.trim(), unitNetWeightKg: x.unitNetWeightKg.trim() || null, remark: x.remark.trim() })); const allocations = this.data.items.map((x, i) => ({ executionLineNumber: i + 1, supplierId: x.supplierId, purchaseCurrency: x.purchaseCurrency, purchaseUnitPrice: x.purchaseUnitPrice.trim() || null, allocatedQuantity: x.quantity.trim(), remark: "" })); const editing = Boolean(this.data.id); const result = await request({ url: editing ? `/api/sales-executions/${encodeURIComponent(this.data.id)}` : "/api/sales-executions", method: editing ? "PATCH" : "POST", data: { sourceType: "DIRECT", ...f, expectedRevision: this.data.revision, creationKey: `mini-${Date.now()}-${Math.random()}`, items, allocations } }); wx.showToast({ title: result.message || (editing ? "执行草稿已更新" : "执行草稿已创建"), icon: "success" }); setTimeout(() => wx.navigateBack(), 600); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ saving: false }); } },
});
