const { request } = require("../../utils/api");
const STATUS = { DRAFT: "草稿", DISPATCHED: "已下发工厂", VOIDED: "已作废" };
Page({
  data: { keyword: "", status: "", statusIndex: 0, statusOptions: ["全部状态", "草稿", "已下发工厂", "已作废"], statusValues: ["", "DRAFT", "DISPATCHED", "VOIDED"], rows: [], total: 0, page: 1, totalPages: 1, canWrite: false, loading: true, error: "" },
  onShow() { this.load(); }, onPullDownRefresh() { this.load().finally(() => wx.stopPullDownRefresh()); },
  onKeyword(e) { this.setData({ keyword: e.detail.value }); }, search() { this.setData({ page: 1 }, () => this.load()); },
  onStatus(e) { const statusIndex = Number(e.detail.value); this.setData({ statusIndex, status: this.data.statusValues[statusIndex], page: 1 }, () => this.load()); },
  async load() { this.setData({ loading: true, error: "" }); try { const params = [`page=${this.data.page}`, "pageSize=20"]; if (this.data.keyword.trim()) params.push(`keyword=${encodeURIComponent(this.data.keyword.trim())}`); if (this.data.status) params.push(`status=${this.data.status}`); const [result, permissionResult] = await Promise.all([request({ url: `/api/sales-executions?${params.join("&")}` }), request({ url: "/api/auth/permissions" })]); const data = result.data || {}; this.setData({ rows: (data.rows || result.executions || []).map((row) => ({ ...row, statusDisplay: STATUS[row.status] || row.status, sourceDisplay: row.sourceType === "QUOTATION" ? "报价转入" : "直接创建", customerDisplay: row.customerShortName || row.customerNameSnapshot || row.customerName || "未命名客户", amountDisplay: `${row.currency || 'CNY'} ${row.totalAmount || row.subtotal || '0'}`, deliveryDisplay: String(row.requestedDeliveryDate || "").slice(0, 10) || "未设置" })), total: data.total || 0, page: data.page || 1, totalPages: data.totalPages || 1, canWrite: (permissionResult.permissions && permissionResult.permissions.writeKeys || []).includes("salesExecution") }); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  open(e) { wx.navigateTo({ url: `/pages/sales-execution-detail/index?id=${encodeURIComponent(e.currentTarget.dataset.id)}` }); }, create() { wx.navigateTo({ url: "/pages/sales-execution-form/index" }); },
  previousPage() { if (this.data.page > 1) this.setData({ page: this.data.page - 1 }, () => this.load()); }, nextPage() { if (this.data.page < this.data.totalPages) this.setData({ page: this.data.page + 1 }, () => this.load()); },
});
