const { request } = require("../../utils/api");
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function requestKey() { return `mini-send-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
Page({
  data: { id: "", loading: true, saving: false, error: "", notice: "", quotation: null, draft: null, channels: ["业务员邮箱／外部邮箱", "微信", "WhatsApp", "电话", "其他"], channelValues: ["EXTERNAL_EMAIL", "WECHAT", "WHATSAPP", "PHONE", "OTHER"], channelIndex: 0, confirmationDate: today(), note: "", recipientEmails: "", ccEmails: "", subject: "", body: "" },
  onLoad(options) { this.setData({ id: options.id || "" }); this.load(); },
  async load() { this.setData({ loading: true, error: "" }); try { const [q, e] = await Promise.all([request({ url: `/api/quotations/${encodeURIComponent(this.data.id)}` }), request({ url: `/api/quotations/${encodeURIComponent(this.data.id)}/email` })]); const quotation = q.quotation || q.data, draft = e.draft || {}; this.setData({ quotation, draft, recipientEmails: (draft.recipientEmails || []).join(", "), ccEmails: (draft.ccEmails || []).join(", "), subject: draft.subject || "", body: draft.body || "" }); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  input(e) { this.setData({ [e.currentTarget.dataset.field]: e.detail.value }); }, chooseChannel(e) { this.setData({ channelIndex: Number(e.detail.value) }); },
  async sendEmail() { if (this.data.saving) return; if (!this.data.recipientEmails.trim() || !this.data.subject.trim() || !this.data.body.trim()) return this.setData({ error: "请完整填写收件邮箱、标题和正文" }); const confirmed = await new Promise((resolve) => wx.showModal({ title: "确认发送报价", content: `将发送 V${this.data.draft.versionNumber || this.data.quotation.currentVersionNumber} 报价及 PDF 附件，是否继续？`, success: (r) => resolve(r.confirm) })); if (!confirmed) return; this.setData({ saving: true, error: "", notice: "" }); try { const result = await request({ url: `/api/quotations/${encodeURIComponent(this.data.id)}/email`, method: "POST", timeout: 60000, data: { versionNumber: this.data.draft.versionNumber, recipientEmails: this.data.recipientEmails, ccEmails: this.data.ccEmails, subject: this.data.subject, body: this.data.body, requestKey: requestKey() } }); this.setData({ notice: result.message || "报价邮件已发送" }); await this.load(); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ saving: false }); } },
  async confirmAccepted() { if (this.data.saving) return; const confirmed = await new Promise((resolve) => wx.showModal({ title: "确认客户已接受", content: "系统会把当前报价标记为客户已接受，并保留登记渠道、日期和操作人。", success: (r) => resolve(r.confirm) })); if (!confirmed) return; this.setData({ saving: true, error: "", notice: "" }); try { const result = await request({ url: `/api/quotations/${encodeURIComponent(this.data.id)}/manual-confirmation`, method: "POST", data: { channel: this.data.channelValues[this.data.channelIndex], confirmationDate: this.data.confirmationDate, note: this.data.note.trim(), expectedVersionNumber: this.data.quotation.currentVersionNumber } }); wx.showToast({ title: "已登记客户接受", icon: "success" }); this.setData({ notice: result.message || "已手动登记客户接受报价" }); setTimeout(() => wx.navigateBack(), 700); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ saving: false }); } },
});
