const { request } = require("../../utils/api");
const TYPES = ["预付款", "中期款", "分批款", "全款", "尾款", "补差款", "退款", "其他"];
const STATUSES = ["待确认", "已到账", "已退回", "已取消"];
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
Page({
  data: { loading: true, saving: false, error: "", orders: [], orderNames: [], orderIndex: -1, types: TYPES, typeIndex: 0, statuses: STATUSES, statusIndex: 0, form: { orderId: "", paymentDate: today(), paymentType: "预付款", amount: "", currency: "CNY", exchangeRate: "1", exchangeRateDate: today(), exchangeRateSource: "系统", exchangeRateType: "人民币", status: "待确认", bankReference: "", remark: "" } },
  onLoad(options) { this.initialOrderId = options.orderId || ""; this.load(); },
  async load() { try { const result = await request({ url: "/api/orders?page=1&pageSize=200" }), orders = result.orders || (result.data && (result.data.rows || result.data.orders)) || []; const orderIndex = this.initialOrderId ? orders.findIndex((x) => x.id === this.initialOrderId) : -1; this.setData({ orders, orderNames: orders.map((x) => `${x.orderNo || '-'} · ${x.customerName || x.customerShortName || ''}`), orderIndex }); if (orderIndex >= 0) this.applyOrder(orderIndex); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  applyOrder(index) { const order = this.data.orders[index], currency = order.currency || "CNY"; this.setData({ orderIndex: index, "form.orderId": order.id, "form.currency": currency, "form.exchangeRate": currency === "CNY" ? "1" : String(order.exchangeRate || ""), "form.exchangeRateDate": today(), "form.exchangeRateSource": currency === "CNY" ? "系统" : "历史录入", "form.exchangeRateType": currency === "CNY" ? "人民币" : "业务汇率" }); },
  chooseOrder(e) { this.applyOrder(Number(e.detail.value)); }, chooseType(e) { const typeIndex = Number(e.detail.value); this.setData({ typeIndex, "form.paymentType": TYPES[typeIndex] }); }, chooseStatus(e) { const statusIndex = Number(e.detail.value); this.setData({ statusIndex, "form.status": STATUSES[statusIndex] }); }, input(e) { this.setData({ [`form.${e.currentTarget.dataset.field}`]: e.detail.value }); },
  async submit() { const f = this.data.form; if (!f.orderId) return this.setData({ error: "请选择关联订单" }); if (!(Number(f.amount) > 0)) return this.setData({ error: "请输入大于 0 的收款金额" }); if (f.currency !== "CNY" && !(Number(f.exchangeRate) > 0)) return this.setData({ error: "外币收款请填写有效汇率" }); this.setData({ saving: true, error: "" }); try { const result = await request({ url: "/api/payments", method: "POST", data: { ...f, amount: Number(f.amount), exchangeRate: Number(f.exchangeRate) } }); wx.showToast({ title: result.message || "收款已保存", icon: "success" }); setTimeout(() => wx.navigateBack(), 650); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ saving: false }); } },
});
