import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const taxRefundService = readFileSync("lib/platform/tax-refunds.ts", "utf8");
const taxCalculationService = readFileSync("lib/platform/export-tax-refund-calculations.ts", "utf8");
const detail = readFileSync("app/modules/tax-refund/detail-components.tsx", "utf8");
const model = readFileSync("app/modules/tax-refund/model.ts", "utf8");
const styles = readFileSync("app/WorkspaceShell.module.css", "utf8");
const schema = readFileSync("prisma/schema.prisma", "utf8");
const ocrIntegration = readFileSync("lib/platform/ocr-integration.ts", "utf8");
const sharedBaseUtils = readFileSync("lib/platform/shared-base-utils.ts", "utf8");
const taxRefundErrors = readFileSync("lib/platform/tax-refund-errors.ts", "utf8");
const taxRefundDetailRoute = readFileSync("app/api/tax-refunds/[orderId]/route.ts", "utf8");
const taxRefundCustomsRoute = readFileSync("app/api/tax-refund/[orderId]/customs-documents/route.ts", "utf8");
const taxRefundCalculationRoute = readFileSync("app/api/tax-refund/[orderId]/calculation/route.ts", "utf8");
const customsRecognitionPanel = detail.match(/function CustomsRecognitionResultPanel[\s\S]*?\n}\n\nfunction SupplierDocumentReturnNotice/)?.[0] || "";

test("customs document tab returns parsed declaration fields and internal raw OCR result", () => {
  const customsSection = taxRefundService.match(/async function getTaxRefundCustomsDocumentsSection[\s\S]*?\n}\n\nasync function getTaxRefundCostDocumentSection/)?.[0] || "";
  assert.match(customsSection, /guardedPrismaFindMany<TaxRefundCustomsItemLight\[\]>/);
  assert.match(customsSection, /rawJson: true/);
  assert.match(customsSection, /customsDeclarationItems: serializedItems/);
  assert.match(customsSection, /guardedPrismaFindMany<Prisma\.OcrRawResultGetPayload<\{\}>\[\]>/);
  assert.match(customsSection, /getTaxRefundCustomsDocumentsSection\.ocrRawResults/);
  assert.match(customsSection, /canReadOcrRawResult\(actor\)/);
  assert.match(customsSection, /guardedPrismaFindMany<TaxRefundDocumentLight\[\]>/);
  assert.match(customsSection, /currentCustomsDocument/);
  assert.match(customsSection, /historicalCustomsDocuments/);
  assert.match(customsSection, /getOcrRawResultByDocumentId\(currentCustomsDocument\.id\)/);
  assert.match(customsSection, /documentId: \{ in: customsDocumentIds \}/);
  assert.match(customsSection, /customsOcrCallLogs/);
  assert.match(taxRefundService, /function serializeTaxRefundCustomsItem/);
  assert.doesNotMatch(taxRefundService.match(/function serializeTaxRefundCustomsItem[\s\S]*?\n}\n\nfunction serializeCustomsOcrRawResult/)?.[0] || "", /domesticConsignor/);
  assert.match(taxRefundService, /serializeStoredOcrRawResult/);
  assert.match(schema, /model OcrRawResult/);
  assert.match(schema, /@@map\("ocr_raw_results"\)/);
});

test("tax refund detail guards missing Prisma models and masks read failures", () => {
  assert.match(sharedBaseUtils, /export function requirePrismaModel/);
  assert.match(sharedBaseUtils, /export async function guardedPrismaFindMany/);
  assert.match(sharedBaseUtils, /Prisma Model \$\{modelName\} not found/);
  assert.match(sharedBaseUtils, /Prisma findMany failed/);
  assert.match(sharedBaseUtils, /modelName/);
  assert.match(sharedBaseUtils, /location/);
  assert.match(sharedBaseUtils, /sql: prismaQueryForLog/);
  assert.match(taxRefundDetailRoute, /taxRefundDataReadFailure/);
  assert.match(taxRefundCustomsRoute, /taxRefundDataReadFailure/);
  assert.match(taxRefundCalculationRoute, /taxRefundDataReadFailure/);
  assert.match(taxRefundErrors, /退税数据读取失败，请联系管理员。/);
  assert.match(taxRefundErrors, /TAX_REFUND_DATA_READ_FAILED/);
});

test("tax refund detail displays customs OCR results and empty-field exception", () => {
  assert.match(model, /customsOcrRawResult\?:/);
  assert.doesNotMatch(model, /domesticConsignor\?: string/);
  assert.match(model, /apiName\?: string/);
  assert.match(model, /rawJson\?: unknown/);
  assert.match(model, /currentCustomsDocument\?: CustomsRecognitionDocument/);
  assert.match(model, /historicalCustomsDocuments\?: CustomsRecognitionDocument\[\]/);
  assert.match(model, /customsOcrCallLogs\?: OcrRawResultView\[\]/);
  assert.match(detail, /function CustomsRecognitionResultPanel/);
  assert.match(detail, /报关单识别结果/);
  assert.match(detail, /当前识别文件/);
  assert.match(detail, /历史识别文件/);
  assert.match(detail, /OCR调用日志/);
  assert.match(detail, /OCR识别成功，但未解析到报关单关键字段。/);
  assert.match(detail, /OCR已识别基础字段，但未解析到报关商品明细。/);
  assert.match(detail, /OCR原始结果未保存，请重新识别。/);
  assert.match(detail, /查看OCR原始结果/);
  assert.match(detail, /canReadCustomsRawResult/);
  assert.match(customsRecognitionPanel, /报关单号/);
  assert.match(customsRecognitionPanel, /申报日期/);
  assert.match(customsRecognitionPanel, /出口日期/);
  assert.match(customsRecognitionPanel, /成交方式/);
  assert.match(customsRecognitionPanel, /币种/);
  assert.match(customsRecognitionPanel, /报关总金额/);
  assert.match(customsRecognitionPanel, /商品名称/);
  assert.match(customsRecognitionPanel, /总金额/);
  assert.doesNotMatch(customsRecognitionPanel, /境内发货人/);
  assert.doesNotMatch(customsRecognitionPanel, /申报单位/);
  assert.doesNotMatch(customsRecognitionPanel, /运输方式/);
  assert.doesNotMatch(customsRecognitionPanel, /提运单号/);
  assert.doesNotMatch(customsRecognitionPanel, /贸易国别/);
  assert.doesNotMatch(customsRecognitionPanel, /监管方式/);
  assert.doesNotMatch(customsRecognitionPanel, /HS编码/);
  assert.doesNotMatch(customsRecognitionPanel, /规格型号/);
  assert.match(styles, /\.customsRecognitionResultCard/);
  assert.match(styles, /\.customsRawResultSection/);
  assert.match(styles, /\.customsOcrFilePanel/);
  assert.match(styles, /\.customsOcrLogList/);
  assert.match(styles, /\.customsOcrRawResult/);
});

test("tax refund calculation requires confirmed declaration items", () => {
  assert.match(taxCalculationService, /saveOcrRawResult/);
  assert.match(taxCalculationService, /logOcrCallFailure/);
  assert.match(taxCalculationService, /customsParsedFromRecognition/);
  assert.match(taxCalculationService, /已识别基础字段，但未解析到商品明细，请人工维护。/);
  assert.match(taxCalculationService, /confirmationStatus: "CONFIRMED"/);
  assert.match(taxCalculationService, /CUSTOMS_DECLARATION_ITEMS_CONFIRM_REQUIRED/);
  assert.match(taxCalculationService, /没有确认报关商品明细，不允许进入退税计算。/);
  assert.match(taxCalculationService, /customsDeclarationNo: firstItem\?\.declarationNo/);
  assert.match(taxCalculationService, /customsDeclarationDate: firstItem\?\.declarationDate/);
  assert.match(detail, /const confirmedItems = items\.filter/);
  assert.match(detail, /没有确认报关商品明细，不允许进入退税计算。请先在“报关商品”中确认并保存。/);
  assert.match(detail, /removeItem/);
  assert.match(styles, /\.taxCalculationBlockedPanel/);
});

test("customs OCR uses structured recognition with table fallback and saves full raw JSON", () => {
  assert.match(ocrIntegration, /CUSTOMS_DECLARATION_KEYS/);
  assert.match(ocrIntegration, /CUSTOMS_TABLE_KEYS/);
  assert.match(ocrIntegration, /recognizeAliyunCustomsDeclaration/);
  assert.match(ocrIntegration, /ALIYUN_RECOGNIZE_TRADE_DOCUMENT_WITH_TABLE/);
  assert.match(ocrIntegration, /rawJson: \{ primary: primaryRawJson, table: tableRawJson \}/);
  assert.match(ocrIntegration, /parsedJson/);
});

test("customs OCR persistence logs empty raw JSON and failed provider calls", () => {
  const rawResultService = readFileSync("lib/platform/ocr-raw-results.ts", "utf8");
  const customsRecognition = readFileSync("lib/platform/customs-recognition.ts", "utf8");
  assert.match(rawResultService, /OCR response received but rawJson was not persisted\./);
  assert.match(rawResultService, /export async function getOcrRawResultByDocumentId/);
  assert.match(rawResultService, /tx\.ocrRawResult\.create/);
  assert.match(rawResultService, /tx\.ocrRawResult\.update/);
  assert.match(customsRecognition, /persistCustomsRecognitionArtifacts/);
  assert.match(customsRecognition, /persistHistoricalCustomsRecognitionArtifacts/);
  assert.match(customsRecognition, /BACKFILLED_HISTORICAL_ORDER_FIELDS/);
  assert.match(customsRecognition, /历史识别未保存原始 OCR 响应/);
  assert.match(customsRecognition, /customs-ocr-result-persisted/);
  assert.match(customsRecognition, /rawJsonSaved/);
  assert.match(customsRecognition, /parsedJsonSaved/);
  assert.match(rawResultService, /export function logOcrCallFailure/);
  assert.match(rawResultService, /provider/);
  assert.match(rawResultService, /apiName/);
  assert.match(rawResultService, /errorCode/);
  assert.match(rawResultService, /errorMessage/);
  assert.match(customsRecognition, /logOcrCallFailure/);
});
