const { request } = require("../../utils/api");
const STATUS = { DRAFT: "草稿", DISPATCHED: "已下发工厂", VOIDED: "已作废" };
Page({
  data: { id: "", loading: true, acting: false, error: "", row: null, canWrite: false },
  onLoad(o) { this.setData({ id: o.id || "" }); }, onShow() { if (this.data.id) this.load(); },
  async load() { this.setData({ loading: true, error: "" }); try { const [result, p] = await Promise.all([request({ url: `/api/sales-executions/${encodeURIComponent(this.data.id)}` }), request({ url: "/api/auth/permissions" })]); const row = result.execution || result.data, canWrite = ((p.permissions && p.permissions.writeKeys) || []).includes("salesExecution"); this.setData({ canWrite, row: { ...row, items: row.items || [], purchaseOrders: row.purchaseOrders || [], statusDisplay: STATUS[row.status] || row.status, sourceDisplay: row.sourceType === "QUOTATION" ? "报价转入" : "直接创建" } }); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  edit() { wx.navigateTo({ url: `/pages/sales-execution-form/index?id=${encodeURIComponent(this.data.id)}` }); },
  async dispatch() { if (this.data.acting) return; const confirmed = await new Promise((resolve) => wx.showModal({ title: "正式下发工厂", content: "下发后销售执行单和工厂采购单将锁定，并按配置发送邮件/短信。", success: (r) => resolve(r.confirm) })); if (!confirmed) return; this.setData({ acting: true, error: "" }); try { const result = await request({ url: `/api/sales-executions/${encodeURIComponent(this.data.id)}/dispatch`, method: "POST", timeout: 65000, data: { expectedRevision: this.data.row.revision } }); wx.showToast({ title: "已正式下发", icon: "success" }); await this.load(); if (result.message) this.setData({ notice: result.message }); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ acting: false }); } },
  async voidExecution() { if (this.data.acting) return; const result = await new Promise((resolve) => wx.showModal({ title: "作废销售执行单", editable: true, placeholderText: "请输入作废原因", confirmColor: "#b3332b", success: resolve })); if (!result.confirm) return; this.setData({ acting: true, error: "" }); try { await request({ url: `/api/sales-executions/${encodeURIComponent(this.data.id)}`, method: "DELETE", data: { expectedRevision: this.data.row.revision, reason: result.content || "小程序作废" } }); wx.showToast({ title: "已作废", icon: "success" }); await this.load(); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ acting: false }); } },
});
