export const INVOICE_FIELD_ALIASES: Record<string, string[]> = {
  invoiceNo: ["invoiceNumber", "invoiceNo", "invoiceNum", "invoice_num", "发票号码", "发票号"],
  invoiceDate: ["invoiceDate", "invoice_date", "date", "开票日期"],
  buyer: [
    "purchaserName",
    "buyerName",
    "purchaser",
    "buyer",
    "buyerTitle",
    "购方名称",
    "购方信息名称",
    "购买方名称",
    "购买方信息名称",
    "购买方",
    "受票方名称",
    "购货方名称",
  ],
  buyerTaxNo: [
    "purchaserTaxNumber",
    "purchaserRegisterNum",
    "purchaserTaxNo",
    "buyerTaxNumber",
    "buyerRegisterNum",
    "buyerTaxNo",
    "buyerTaxId",
    "购方税号",
    "购方信息纳税人识别号",
    "购买方纳税人识别号",
    "购买方税号",
    "购买方信息纳税人识别号",
    "受票方税号",
    "受票方纳税人识别号",
  ],
  seller: [
    "sellerName",
    "sellerTitle",
    "seller",
    "salesName",
    "salesPartyName",
    "销方名称",
    "销方信息名称",
    "销售方名称",
    "销售方信息名称",
    "销售方",
    "销货方名称",
    "出售方名称",
    "开票方名称",
  ],
  sellerTaxNo: [
    "sellerTaxNumber",
    "sellerRegisterNum",
    "sellerTaxNo",
    "sellerTaxId",
    "salesTaxNumber",
    "salesTaxNo",
    "销方税号",
    "销方信息纳税人识别号",
    "销售方纳税人识别号",
    "销售方税号",
    "销售方信息纳税人识别号",
    "开票方税号",
    "开票方纳税人识别号",
  ],
  amountWithTax: [
    "totalAmount",
    "amountInFiguers",
    "amountInFigures",
    "totalAmountInFigures",
    "totalAmountWithTax",
    "amountWithTax",
    "价税合计",
    "价税合计小写",
    "小写金额",
    "含税金额",
  ],
  amountWithoutTax: [
    "invoiceAmountPreTax",
    "amountWithoutTax",
    "totalAmountWithoutTax",
    "sumAmount",
    "totalAmountPreTax",
    "合计金额",
    "金额合计",
    "不含税金额",
  ],
  taxAmount: ["invoiceTax", "totalTax", "taxAmount", "sumTax", "合计税额", "税额合计"],
  taxRate: ["taxRate", "commodityTaxRate", "itemTaxRate", "税率"],
  productName: [
    "itemName",
    "commodityName",
    "productName",
    "goodsName",
    "serviceName",
    "货物或应税劳务、服务名称",
    "货物或应税劳务服务名称",
    "项目名称",
    "商品名称",
    "产品名称",
    "服务名称",
  ],
  specModel: ["specification", "specModel", "model", "规格型号"],
  unit: ["unit", "单位"],
  quantity: ["quantity", "数量"],
  unitPrice: ["unitPrice", "price", "单价"],
};

export const DETAIL_ARRAY_KEYS = [
  "invoiceDetails",
  "details",
  "items",
  "commodities",
  "invoiceItems",
  "货物明细",
  "明细",
];

export type KeyValueEntry = {
  key: string;
  normalizedKey: string;
  value: unknown;
};

export const PARTY_MARKERS = {
  buyer: ["purchaser", "buyer", "购方", "购买方", "受票方", "购货方"],
  seller: ["seller", "sales", "销方", "销售方", "销货方", "出售方", "开票方"],
};

export const PARTY_NAME_MARKERS = ["name", "title", "名称", "纳税人名称"];
export const PARTY_TAX_MARKERS = ["taxnumber", "taxno", "taxid", "registernum", "registercode", "纳税人识别号", "统一社会信用代码", "税号"];
