export const LOGISTICS_FEE_COST_SOURCE_TYPE = "LOGISTICS_FEE";
export const LEGACY_LOGISTICS_EXPENSE_COST_SOURCE_TYPE = "LOGISTICS_EXPENSE";
export const LOGISTICS_GENERATED_COST_SOURCE_TYPES = [
  LEGACY_LOGISTICS_EXPENSE_COST_SOURCE_TYPE,
  LOGISTICS_FEE_COST_SOURCE_TYPE,
];

export function isLogisticsGeneratedCostSourceType(value: unknown) {
  return LOGISTICS_GENERATED_COST_SOURCE_TYPES.includes(String(value || ""));
}
