import { NOTIFICATION_TYPES, type NotificationTypeDefinition } from "./notification-definition-types";

const TRACKING_VARIABLES = [
  { key: "orderNo", label: "订单号", required: true },
  { key: "blNo", label: "提单号" },
  { key: "containerNo", label: "箱号" },
  { key: "statusText", label: "当前状态" },
  { key: "eventText", label: "最新节点" },
  { key: "eventTime", label: "节点时间" },
  { key: "eta", label: "预计到港" },
  { key: "vesselVoyage", label: "船名航次" },
  { key: "trackingUrl", label: "跟踪详情链接" },
];

const CUSTOMER_TRACKING_VARIABLE_LABELS: Record<string, string> = {
  orderNo: "Order No.",
  blNo: "B/L No.",
  containerNo: "Container No.",
  statusText: "Current Status",
  eventText: "Latest Event",
  eventTime: "Event Time",
  eta: "Estimated Arrival",
  vesselVoyage: "Vessel / Voyage",
  trackingUrl: "Tracking URL",
};

export const FREIGHTOWER_NOTIFICATION_TYPE_DEFINITIONS: NotificationTypeDefinition[] = [
  {
    type: NOTIFICATION_TYPES.FREIGHTOWER_TRACKING_UPDATE,
    name: "物流跟踪通知（内部中文）",
    module: "物流跟踪",
    description: "物流信息变化后，使用中文邮件通知管理员和订单业务员。",
    editable: true,
    supportsAttachments: false,
    subjectTemplate: "【物流跟踪更新】订单 {orderNo} / 提单 {blNo}",
    bodyTemplate: [
      "您好，",
      "",
      "订单 {orderNo} 的物流跟踪信息发生变化，请查看以下内容：",
      "",
      "订单号：{orderNo}",
      "提单号：{blNo}",
      "箱号：{containerNo}",
      "当前状态：{statusText}",
      "最新节点：{eventText}",
      "节点时间：{eventTime}",
      "预计到港：{eta}",
      "船名航次：{vesselVoyage}",
      "",
      "如邮件标记为异常预警，请及时确认并跟进。",
      "",
      "查看实时物流跟踪：{trackingUrl}",
      "",
      "NEXTWOOD 物流跟踪团队",
    ].join("\n"),
    variables: TRACKING_VARIABLES,
    ccAdminEmails: false,
  },
  {
    type: NOTIFICATION_TYPES.FREIGHTOWER_TRACKING_CUSTOMER_UPDATE,
    name: "Shipment Tracking Update (Customer English)",
    module: "物流跟踪",
    description: "物流信息变化后，使用英文邮件通知客户资料中绑定的主联系邮箱。",
    editable: true,
    supportsAttachments: false,
    subjectTemplate: "Shipment Tracking Update | Order {orderNo} | B/L {blNo}",
    bodyTemplate: [
      "Dear Customer,",
      "",
      "The shipment status for Order {orderNo} has been updated.",
      "",
      "Order No.: {orderNo}",
      "B/L No.: {blNo}",
      "Container No.: {containerNo}",
      "Current Status: {statusText}",
      "Latest Event: {eventText}",
      "Event Time: {eventTime}",
      "Estimated Arrival: {eta}",
      "Vessel / Voyage: {vesselVoyage}",
      "",
      "View live tracking: {trackingUrl}",
      "",
      "Tracking information is provided by a third-party data service. Please confirm critical dates with the carrier.",
      "",
      "NEXTWOOD Tracking Team",
    ].join("\n"),
    variables: TRACKING_VARIABLES.map((variable) => ({
      ...variable,
      label: CUSTOMER_TRACKING_VARIABLE_LABELS[variable.key] || variable.key,
    })),
    ccAdminEmails: false,
  },
  {
    type: NOTIFICATION_TYPES.FREIGHTOWER_PORT_ROLLOVER_ALERT,
    name: "港区甩箱预警（中文）",
    module: "物流跟踪",
    description: "港区出现甩箱异常时，使用中文邮件通知管理员和订单业务员。",
    editable: true,
    supportsAttachments: false,
    subjectTemplate: "【港区甩箱预警】订单 {orderNo} / 提单 {blNo}",
    bodyTemplate: [
      "您好，", "", "订单 {orderNo} 出现港区甩箱预警，请立即跟进。", "",
      "提单号：{blNo}", "箱号：{containerNo}", "最新节点：{eventText}",
      "预警时间：{eventTime}", "预计到港：{eta}", "船名航次：{vesselVoyage}", "",
      "请联系货代或船公司，确认后续船名、航次及新的预计到港时间。", "",
      "查看实时物流跟踪：{trackingUrl}", "", "NEXTWOOD 物流跟踪团队",
    ].join("\n"),
    variables: TRACKING_VARIABLES,
    ccAdminEmails: false,
  },
  {
    type: NOTIFICATION_TYPES.FREIGHTOWER_PORT_OPERATION_ALERT,
    name: "港区开截港通知（中文）",
    module: "物流跟踪",
    description: "港区开放、开港时间变更或截港时间变更时，使用中文邮件通知管理员和订单业务员。",
    editable: true,
    supportsAttachments: false,
    subjectTemplate: "【港区开截港通知】订单 {orderNo} / 提单 {blNo}",
    bodyTemplate: [
      "您好，", "", "订单 {orderNo} 的港区开截港状态发生变化，请及时查看。", "",
      "提单号：{blNo}", "箱号：{containerNo}", "当前状态：{statusText}",
      "最新节点：{eventText}", "节点时间：{eventTime}", "船名航次：{vesselVoyage}", "",
      "如为港区已开放，请及时安排进箱；如为开港或截港时间变更，请同步调整装箱、进港及报关安排。", "",
      "查看实时物流跟踪：{trackingUrl}", "", "NEXTWOOD 物流跟踪团队",
    ].join("\n"),
    variables: TRACKING_VARIABLES,
    ccAdminEmails: false,
  },
  {
    type: NOTIFICATION_TYPES.FREIGHTOWER_CUSTOMS_ALERT,
    name: "中国海关跟踪通知（中文）",
    module: "物流跟踪",
    description: "中国海关节点变化时，使用中文邮件通知管理员和订单业务员。",
    editable: true,
    supportsAttachments: false,
    subjectTemplate: "【中国海关跟踪通知】订单 {orderNo} / 提单 {blNo}",
    bodyTemplate: [
      "您好，", "", "订单 {orderNo} 的中国海关状态发生变化，请及时查看。", "",
      "提单号：{blNo}", "箱号：{containerNo}", "海关状态：{statusText}",
      "最新节点：{eventText}", "节点时间：{eventTime}", "船名航次：{vesselVoyage}", "",
      "如为查验、退单或删单等异常状态，请联系报关行核实进度及所需资料。", "",
      "查看实时物流跟踪：{trackingUrl}", "", "NEXTWOOD 物流跟踪团队",
    ].join("\n"),
    variables: TRACKING_VARIABLES,
    ccAdminEmails: false,
  },
];
