import { standardFilenameForDocument } from "./shared-constants";

export function dateTimeToIso(value: Date | string | null | undefined) {
  if (!value) return "";
  const date = value instanceof Date ? value : new Date(value);
  return Number.isFinite(date.getTime()) ? date.toISOString() : "";
}

export type OrderDocumentStatusLike = {
  documentType?: string | null;
  uploadStatus?: string | null;
  deletedAt?: Date | string | null;
};
export type ShippingNotificationCustomerLike = {
  enableAutoShippingDocsNotification?: boolean | null;
  autoSendDocumentTypes?: unknown;
};
export type ShippingNotificationRowLike = {
  id?: string | null;
  orderId?: string | null;
  customerId?: string | null;
  invoiceId?: string | null;
  sentById?: string | null;
  sentBy?: { name?: string | null } | null;
  recipientEmails?: unknown;
  ccEmails?: unknown;
  documentTypes?: unknown;
  attachmentFileIds?: unknown;
  sendStatus?: string | null;
  sendMode?: string | null;
  emailLanguage?: string | null;
  emailSubject?: string | null;
  emailBody?: string | null;
  errorMessage?: string | null;
  sentAt?: Date | string | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type ShippingNotificationOrderLike = {
  id?: string | null;
  customerId?: string | null;
  documents?: unknown[] | null;
  customer?: ShippingNotificationCustomerLike | null;
};
export type CustomsRecognitionOrderLike = {
  customsDeclarationNo?: string | null;
  customsDeclarationDate?: Date | null;
  customsParsedAt?: Date | string | null;
  customsParseStatus?: string | null;
  customsDeclarationParseSource?: string | null;
  customsParseMessage?: string | null;
};
export type OrderDocumentOrderOverride = Parameters<typeof standardFilenameForDocument>[1];
export type UserLike = {
  id?: string | null;
  name?: string | null;
  email?: string | null;
  role?: string | null;
  phone?: string | null;
  avatarInitials?: string | null;
  defaultLanguage?: string | null;
  customPermissions?: unknown;
  supplierId?: string | null;
  supplierOperator?: { supplierName?: string | null; supplierType?: string | null } | null;
  mustChangePassword?: boolean | null;
  approvalStatus?: string | null;
  isActive?: boolean | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type CustomerLike = Record<string, unknown> & {
  id?: string | null;
  name?: string | null;
  shortName?: string | null;
  country?: string | null;
  defaultCurrency?: string | null;
  salespersonUserId?: string | null;
  salesperson?: UserLike | null;
  commissionRate?: unknown;
  commissionStatus?: string | null;
  contactPerson?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  enableAutoShippingDocsNotification?: boolean | null;
  shippingDocsEmails?: unknown;
  shippingDocsCcEmails?: unknown;
  autoSendDocumentTypes?: unknown;
  clearanceEmailLanguage?: string | null;
  remark?: string | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type SupplierLike = Record<string, unknown> & {
  id?: string | null;
  supplierName?: string | null;
  supplierType?: string | null;
  country?: string | null;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  invoiceTitle?: string | null;
  taxNumber?: string | null;
  bankName?: string | null;
  bankAccount?: string | null;
  remark?: string | null;
  status?: string | null;
  allowDomesticLogisticsEntry?: boolean | null;
  allowLogisticsExpenseEntry?: boolean | null;
  allowLogisticsInvoiceUpload?: boolean | null;
  allowFactoryDocumentUpload?: boolean | null;
  isDefaultLogisticsSupplier?: boolean | null;
  allowedLogisticsCostTypes?: unknown;
  createdBy?: UserLike | null;
  updatedBy?: UserLike | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type PaymentOrderLike = Record<string, unknown> & {
  orderNo?: string | null;
  customer?: CustomerLike | null;
  customerNameSnapshot?: string | null;
  country?: string | null;
  salesperson?: UserLike | null;
  taxArchived?: boolean | null;
  taxRefundStatus?: string | null;
};
export type PaymentLike = Record<string, unknown> & {
  id?: string | null;
  orderId?: string | null;
  order?: PaymentOrderLike | null;
  paymentDate?: Date | string | null;
  currency?: string | null;
  exchangeRate?: unknown;
  exchangeRateDate?: Date | string | null;
  exchangeRateSource?: string | null;
  exchangeRateType?: string | null;
  amount?: unknown;
  amountCny?: unknown;
  paymentType?: string | null;
  status?: string | null;
  bankReference?: string | null;
  remark?: string | null;
  createdBy?: UserLike | null;
  updatedBy?: UserLike | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type CostOrderLike = PaymentOrderLike & {
  id?: string | null;
  blNo?: string | null;
  customerId?: string | null;
  currency?: string | null;
  exchangeRate?: unknown;
  status?: string | null;
  commissionStatus?: string | null;
  commissionSettlementRecords?: Array<{ id?: string | null }> | null;
  taxRefundArchivedAt?: Date | string | null;
};
export type CostDocumentLike = Record<string, unknown> & {
  id?: string | null;
  orderId?: string | null;
  costId?: string | null;
  supplierId?: string | null;
  factoryDocumentRequestId?: string | null;
  relatedModule?: string | null;
  order?: CostOrderLike | null;
  supplier?: SupplierLike | null;
  cost?: CostLike | null;
  costType?: string | null;
  documentType?: string | null;
  fileName?: string | null;
  fileUrl?: string | null;
  originalFilename?: string | null;
  originalName?: string | null;
  fileSize?: unknown;
  mimeType?: string | null;
  uploadStatus?: string | null;
  uploadProgress?: unknown;
  uploadedBy?: UserLike | null;
  uploadedAt?: Date | string | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
  source?: string | null;
};
export type CostLike = Record<string, unknown> & {
  id?: string | null;
  orderId?: string | null;
  orderNo?: string | null;
  blNo?: string | null;
  order?: CostOrderLike | null;
  supplierId?: string | null;
  supplier?: SupplierLike | null;
  supplierNameSnapshot?: string | null;
  vendorName?: string | null;
  costType?: string | null;
  currency?: string | null;
  exchangeRate?: unknown;
  exchangeRateDate?: Date | string | null;
  exchangeRateSource?: string | null;
  exchangeRateType?: string | null;
  amount?: unknown;
  amountCny?: unknown;
  status?: string | null;
  voidedAt?: Date | string | null;
  voidedById?: string | null;
  voidReason?: string | null;
  restoredAt?: Date | string | null;
  restoredById?: string | null;
  restoreReason?: string | null;
  paymentStatus?: string | null;
  costConfirmed?: boolean | null;
  costConfirmedAt?: Date | string | null;
  paymentDate?: Date | string | null;
  paid?: boolean | null;
  paidAt?: Date | string | null;
  paymentVoucherUrl?: string | null;
  paymentVoucherFileName?: string | null;
  paymentVoucherMimeType?: string | null;
  paymentVoucherUploadedAt?: Date | string | null;
  paymentVoucherStorageKey?: string | null;
  paymentVoucherBucket?: string | null;
  invoiceStatus?: string | null;
  sourceType?: string | null;
  sourceId?: string | null;
  remark?: string | null;
  documents?: CostDocumentLike[] | null;
  generatedLogisticsExpense?: unknown;
  supplierDocumentRequests?: Array<{ id?: string | null; deletedAt?: Date | string | null }> | null;
  createdBy?: UserLike | null;
  updatedBy?: UserLike | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type DomesticLogisticsTransportItemLike = Record<string, unknown> & {
  id?: string | null;
  logisticsInfoId?: string | null;
  containerNo?: string | null;
  containerType?: string | null;
  sealNo?: string | null;
  truckPlateNo?: string | null;
  trailerPlateNo?: string | null;
  departureDate?: Date | string | null;
  departurePlace?: string | null;
  arrivalPlace?: string | null;
  cargoName?: string | null;
  remark?: string | null;
  sortOrder?: unknown;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
};
export type DomesticLogisticsInfoLike = Record<string, unknown> & {
  id?: string | null;
  orderId?: string | null;
  transportType?: string | null;
  truckPlateNo?: string | null;
  trailerPlateNo?: string | null;
  departurePlace?: string | null;
  destinationPlace?: string | null;
  departureDate?: Date | string | null;
  expressTrackingNo?: string | null;
  cargoDescription?: string | null;
  transportItems?: DomesticLogisticsTransportItemLike[] | null;
  remarkTextManualEdited?: boolean | null;
  remarkText?: string | null;
  exportInvoice?: unknown;
  submittedByUserId?: string | null;
  submittedBy?: UserLike | null;
  submittedAt?: Date | string | null;
  submitterRole?: string | null;
  unlockedByUserId?: string | null;
  unlockedAt?: Date | string | null;
  correctionRequested?: boolean | null;
  correctionReason?: string | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
  deletedAt?: Date | string | null;
};

export function asLooseRecord<T extends Record<string, unknown>>(value: unknown): T {
  return (value && typeof value === "object" ? value : {}) as T;
}
