export type SupplierTaxContractItemDraft = {
  rowId?: string;
  lineNo: number;
  purchaseOrderItemId: string;
  customsItemNo: string;
  customsCommodityCode: string;
  productName: string;
  unit: string;
  quantity: string;
  declaredQuantity: string;
  unitPriceWithTax: string;
  amountWithTax: string;
};

export type SupplierTaxContractDraft = {
  contractNo: string;
  customerOrderNo: string;
  orderId: string;
  costId: string;
  purchaseOrderId: string;
  purchaseOrderNo: string;
  customsDocumentId: string;
  customsDeclarationNo: string;
  supplierId: string;
  supplierName: string;
  supplierTaxNumber: string;
  supplierAddress: string;
  supplierPhone: string;
  supplierBankName: string;
  supplierBankAccount: string;
  buyerBusinessEntityId: string;
  buyerName: string;
  buyerTaxNumber: string;
  buyerAddress: string;
  buyerPhone: string;
  buyerBankName: string;
  buyerBankAccount: string;
  signingPlace: string;
  signingDate: string;
  latestDeliveryDate: string;
  currency: string;
  totalAmountWithTax: string;
  items: SupplierTaxContractItemDraft[];
  ocrOriginalItems?: SupplierTaxContractItemDraft[];
  customsSnapshot: Array<Record<string, unknown>>;
  warnings: string[];
  blockingIssues: string[];
  generatedAt: string;
  manualEditedAt?: string;
  manualEditedById?: string;
  ocrRequestIds: string[];
  sourceType?: string;
  transitionSettlementId?: string;
};
