const { request } = require("../../utils/api");
const COST_TYPES = ["工厂货款", "原材料货款", "采购货款", "产品货款", "银行手续费", "样品费", "国外佣金", "其他费用"];
const LOGISTICS_TYPES = ["拖车费", "报关费", "港杂费", "海运费", "国内物流费", "国内拖车费"];
const TRANSPORT_TYPES = ["车辆运输", "快递运输", "多式联运", "散货进舱"], TRANSPORT_VALUES = ["TRUCK", "EXPRESS", "MULTIMODAL", "BULK_WAREHOUSE"];
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
Page({
  data: { kind: "", title: "新增记录", loading: true, saving: false, error: "", orders: [], orderNames: [], orderIndex: -1, suppliers: [], allSuppliers: [], supplierNames: [], supplierIndex: -1, currencies: ["CNY", "USD"], currencyIndex: 0, costTypes: COST_TYPES, costTypeIndex: 0, logisticsTypes: LOGISTICS_TYPES, logisticsTypeIndex: 0, transportTypes: TRANSPORT_TYPES, transportIndex: 0, form: { orderId: "", supplierId: "", amount: "", currency: "CNY", exchangeRate: "1", paymentStatus: "待支付", costConfirmed: false, remark: "", transportType: "TRUCK", expressTrackingNo: "", truckPlateNo: "", trailerPlateNo: "", departureDate: today(), departurePlace: "", destinationPlace: "", cargoDescription: "", appliedContainerCount: "1", auditStatus: "待审核" } },
  onLoad(options) { const kind = options.kind || "", titles = { cost: "新增成本", domestic: "录入物流信息", logisticsFee: "新增物流费用" }; this.setData({ kind, title: titles[kind] || "新增记录" }); wx.setNavigationBarTitle({ title: titles[kind] || "新增记录" }); this.load(); },
  async load() { try { const orderUrl = this.data.kind === "domestic" ? "/api/domestic-logistics?page=1&pageSize=200" : this.data.kind === "logisticsFee" ? "/api/logistics-costs/orders?page=1&pageSize=200" : "/api/orders?page=1&pageSize=200"; const [o, s] = await Promise.all([request({ url: orderUrl }), request({ url: "/api/suppliers/available" })]), data = o.data || {}, orders = o.rows || o.orders || data.rows || data.orders || [], allSuppliers = (s.suppliers || []).filter((x) => x.status !== "停用"); this.setData({ orders, orderNames: orders.map((x) => `${x.orderNo || '-'} · ${x.customerName || x.customerShortName || ''}`), allSuppliers, suppliers: allSuppliers, supplierNames: allSuppliers.map((x) => `${x.supplierName || x.name} · ${x.supplierType || ''}`) }); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  chooseOrder(e) { const orderIndex = Number(e.detail.value), order = this.data.orders[orderIndex], orderId = order.id || order.orderId; let suppliers = this.data.allSuppliers; if (this.data.kind === "logisticsFee" && (order.logisticsSuppliers || []).length) suppliers = order.logisticsSuppliers; this.setData({ orderIndex, "form.orderId": orderId, suppliers, supplierNames: suppliers.map((x) => `${x.supplierName || x.name} · ${x.supplierType || ''}`), supplierIndex: -1, "form.supplierId": "" }); },
  chooseSupplier(e) { const supplierIndex = Number(e.detail.value); this.setData({ supplierIndex, "form.supplierId": this.data.suppliers[supplierIndex].id }); },
  chooseCurrency(e) { const currencyIndex = Number(e.detail.value), currency = this.data.currencies[currencyIndex]; this.setData({ currencyIndex, "form.currency": currency, "form.exchangeRate": currency === "CNY" ? "1" : "" }); },
  chooseCostType(e) { this.setData({ costTypeIndex: Number(e.detail.value) }); }, chooseLogisticsType(e) { this.setData({ logisticsTypeIndex: Number(e.detail.value) }); }, chooseTransport(e) { const transportIndex = Number(e.detail.value); this.setData({ transportIndex, "form.transportType": TRANSPORT_VALUES[transportIndex] }); },
  input(e) { this.setData({ [`form.${e.currentTarget.dataset.field}`]: e.detail.value }); },
  validate() { const f = this.data.form; if (!f.orderId) return "请选择关联订单"; if (this.data.kind !== "domestic" && !f.supplierId) return "请选择供应商"; if (this.data.kind !== "domestic" && (!(Number(f.amount) > 0) || !(Number(f.exchangeRate) > 0))) return "请填写有效金额和汇率"; if (this.data.kind === "domestic" && f.transportType === "EXPRESS" && (!f.expressTrackingNo.trim() || !f.destinationPlace.trim() || !f.cargoDescription.trim())) return "请完整填写快递单号、到达地和货物名称"; if (this.data.kind === "domestic" && f.transportType !== "EXPRESS" && (!f.truckPlateNo.trim() || !f.departureDate || !f.departurePlace.trim() || !f.destinationPlace.trim() || !f.cargoDescription.trim())) return "请完整填写车辆、日期、起运地、到达地和货物名称"; return ""; },
  async submit() { const message = this.validate(); if (message) return this.setData({ error: message }); const f = this.data.form; this.setData({ saving: true, error: "" }); try { let url = "/api/costs", data; if (this.data.kind === "cost") data = { orderId: f.orderId, items: [{ supplierId: f.supplierId, costType: COST_TYPES[this.data.costTypeIndex], amount: Number(f.amount), currency: f.currency, exchangeRate: Number(f.exchangeRate), exchangeRateSource: f.currency === "CNY" ? "系统" : "历史录入", exchangeRateType: f.currency === "CNY" ? "人民币" : "业务汇率", paymentStatus: "待支付", costConfirmed: false, remark: f.remark.trim() }] }; else if (this.data.kind === "logisticsFee") { url = "/api/logistics-costs"; data = { orderId: f.orderId, supplierId: f.supplierId, auditStatus: f.auditStatus, items: [{ costType: LOGISTICS_TYPES[this.data.logisticsTypeIndex], billingMethod: "按柜", amount: Number(f.amount), billingQuantity: Number(f.appliedContainerCount), appliedContainerCount: Number(f.appliedContainerCount), currency: f.currency, exchangeRate: Number(f.exchangeRate), remark: f.remark.trim() }] }; } else { url = "/api/domestic-logistics"; const isExpress = f.transportType === "EXPRESS", item = { truckPlateNo: f.truckPlateNo.trim(), trailerPlateNo: f.trailerPlateNo.trim(), departureDate: f.departureDate, departurePlace: f.departurePlace.trim(), arrivalPlace: f.destinationPlace.trim(), cargoName: f.cargoDescription.trim(), remark: f.remark.trim() }; data = { orderId: f.orderId, transportType: f.transportType, truckPlateNo: isExpress ? "" : item.truckPlateNo, trailerPlateNo: isExpress ? "" : item.trailerPlateNo, departurePlace: isExpress ? "" : item.departurePlace, departureDate: isExpress ? "" : item.departureDate, expressTrackingNo: isExpress ? f.expressTrackingNo.trim() : "", destinationPlace: f.destinationPlace.trim(), cargoDescription: f.cargoDescription.trim(), transportItems: isExpress ? [] : [item], remarkText: f.remark.trim(), remarkTextManualEdited: true }; } const result = await request({ url, method: "POST", data }); wx.showToast({ title: result.message || "记录已保存", icon: "success" }); setTimeout(() => wx.navigateBack(), 650); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ saving: false }); } },
});
