export type FactoryPurchaseOrderStatus = "DRAFT" | "DISPATCHED" | "ACCEPTED" | "DELIVERY_PROPOSED" | "REJECTED" | "VOIDED";
export type FactoryPurchaseOrderProductionStatus = "WAITING_SUPPLIER" | "WAITING_PREPAYMENT" | "READY" | "IN_PRODUCTION" | "COMPLETED";

export type FactoryPurchaseOrderPayment = {
  id: string;
  sequenceNo?: number;
  kind?: "PREPAYMENT" | "BALANCE" | string;
  amount?: string | number | null;
  currency?: string | null;
  paidAt?: string | null;
  bankReference?: string | null;
  remark?: string | null;
  status?: "CONFIRMED" | "VOIDED" | string;
  voidedAt?: string | null;
  voidReason?: string | null;
};

export type FactoryPurchaseOrderAdjustment = {
  id: string;
  sequenceNo?: number;
  kind?: "TEMPORARY_FEE" | "DELAY_PENALTY" | "OTHER" | string;
  direction?: "INCREASE" | "DECREASE" | string;
  amount?: string | number | null;
  currency?: string | null;
  description?: string | null;
  occurredAt?: string | null;
  status?: "PROVISIONAL" | "CONFIRMED" | "VOIDED" | string;
};

export type FactoryPurchaseOrderSettlement = {
  id: string;
  baseAmount?: string | number | null;
  increaseAmount?: string | number | null;
  decreaseAmount?: string | number | null;
  delayDays?: number | null;
  delayPenaltyAmount?: string | number | null;
  finalPayableAmount?: string | number | null;
  currency?: string | null;
  exchangeRate?: string | number | null;
  exchangeRateDate?: string | null;
  paidAmountAtSettlement?: string | number | null;
  currentPaidAmount?: string | number | null;
  remainingAmount?: string | number | null;
  status?: "PENDING_PAYMENT" | "SETTLED" | string;
  settledAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  createdBy?: { id?: string; name?: string | null } | null;
  settledBy?: { id?: string; name?: string | null } | null;
};

export type PurchaseOrderItem = {
  id?: string;
  executionItemId?: string | null;
  salesExecutionItemId?: string | null;
  productDescription?: string | null;
  productNameSnapshot?: string | null;
  specificationSnapshot?: string | null;
  descriptionSnapshot?: string | null;
  unitSnapshot?: string | null;
  allocatedQuantity?: string | number | null;
  quantity?: string | number | null;
  purchaseUnitPrice?: string | number | null;
  supplierConfirmedUnitPrice?: string | number | null;
  effectivePurchaseUnitPrice?: string | number | null;
  unitPrice?: string | number | null;
  amount?: string | number | null;
  supplierConfirmedAmount?: string | number | null;
  effectiveAmount?: string | number | null;
  supplierPriceConfirmedAt?: string | null;
  remark?: string | null;
};

export type FactoryPurchaseOrder = {
  id: string;
  revision?: number | null;
  sequenceNo?: number | null;
  replacementForId?: string | null;
  poNo?: string | null;
  purchaseOrderNo?: string | null;
  supplierId?: string | null;
  supplier?: { id: string; supplierName?: string | null; name?: string | null } | null;
  supplierNameSnapshot?: string | null;
  purchaseCurrency?: string | null;
  currency?: string | null;
  subtotal?: string | number | null;
  effectiveSubtotal?: string | number | null;
  totalAmount?: string | number | null;
  status?: FactoryPurchaseOrderStatus | string | null;
  requestedDeliveryDate?: string | null;
  paymentTerm?: string | null;
  prepaymentRatio?: string | number | null;
  prepaymentRequiredAmount?: string | number | null;
  paidPrepaymentAmount?: string | number | null;
  prepaymentRequiredBeforeProduction?: boolean;
  initialSupplierDeliveryDate?: string | null;
  confirmedSupplierDeliveryDate?: string | null;
  penaltyBaseAmount?: string | number | null;
  delayGraceDays?: number | null;
  delayPenaltyRatePerDay?: string | number | null;
  delayPenaltyCapRatio?: string | number | null;
  estimatedPenaltyDays?: number | null;
  estimatedPenaltyAmount?: string | number | null;
  productionStatus?: FactoryPurchaseOrderProductionStatus | string | null;
  productionStartedAt?: string | null;
  productionStartedBy?: { id?: string; name?: string | null } | null;
  productionCompletedAt?: string | null;
  productionCompletedBy?: { id?: string; name?: string | null } | null;
  actualDeliveryDate?: string | null;
  actualDeliveryRecordedAt?: string | null;
  actualDeliveryRecordedBy?: { id?: string; name?: string | null } | null;
  dispatchedAt?: string | null;
  dispatchedBy?: { id?: string; name?: string | null } | null;
  dispatchVersionNumber?: number | null;
  dispatchEmailStatus?: string | null;
  dispatchEmailSentAt?: string | null;
  dispatchEmailError?: string | null;
  supplierDeliveryDate?: string | null;
  supplierResponseRemark?: string | null;
  supplierResponseSequence?: number | null;
  supplierResponseHistory?: Array<{
    sequence?: number;
    action?: string;
    deliveryDate?: string | null;
    remark?: string | null;
    respondedAt?: string | null;
    internalDecision?: string | null;
    internalDecisionRemark?: string | null;
    internalDecidedAt?: string | null;
    internalDecidedBy?: { id?: string; name?: string | null } | null;
  }>;
  respondedAt?: string | null;
  respondedBy?: { id?: string; name?: string | null } | null;
  payments?: FactoryPurchaseOrderPayment[];
  adjustments?: FactoryPurchaseOrderAdjustment[];
  settlement?: FactoryPurchaseOrderSettlement | null;
  remark?: string | null;
  items?: PurchaseOrderItem[];
};
