export type FactoryPurchaseOrderStatus = "DRAFT" | "DISPATCHED" | "ACCEPTED" | "DELIVERY_PROPOSED" | "REJECTED" | "VOIDED";
export type FactoryPurchaseOrderProductionStatus = "WAITING_SUPPLIER" | "WAITING_PREPAYMENT" | "READY" | "IN_PRODUCTION" | "COMPLETED";
export type FactoryConfirmationSource = "SUPPLIER_PORTAL" | "INTERNAL_OFFLINE";
export type FactoryConfirmationChannel = "PORTAL" | "WECHAT" | "PHONE" | "EMAIL" | "PAPER" | "OTHER";
export type FactoryConfirmationEvidence = {
  id?: string;
  fileName?: string | null;
  originalFileName?: string | null;
  mimeType?: string | null;
  fileSize?: number | null;
  uploadedAt?: string | null;
  uploadedBy?: { id?: string; name?: string | null } | null;
  previewUrl?: string | null;
  downloadUrl?: string | null;
};

export type FactoryPurchaseOrderDispatchAttachment = FactoryConfirmationEvidence & {
  previewKind?: string | null;
};

export type FactoryPurchaseOrderConfirmationEvent = {
  key: string;
  eventId?: string;
  kind?: "SUPPLIER_RESPONSE" | "PRODUCTION_COMPLETION" | string;
  action?: string | null;
  deliveryDate?: string | null;
  priceChanges?: Array<{
    purchaseOrderItemId?: string;
    unitPrice?: string | number | null;
    amount?: string | number | null;
  }>;
  source?: FactoryConfirmationSource | string | null;
  channel?: FactoryConfirmationChannel | string | null;
  supplierContact?: string | null;
  occurredAt?: string | null;
  recordedAt?: string | null;
  recordedBy?: { id?: string; name?: string | null } | null;
  remark?: string | null;
  evidenceNote?: string | null;
  evidence?: string | FactoryConfirmationEvidence | null;
};

export type FactoryPurchaseOrderPayment = {
  id: string;
  sequenceNo?: number;
  kind?: "PREPAYMENT" | "BALANCE" | "REFUND" | string;
  amount?: string | number | null;
  currency?: string | null;
  paidAt?: string | null;
  bankReference?: string | null;
  remark?: string | null;
  status?: "CONFIRMED" | "VOIDED" | string;
  voidedAt?: string | null;
  voidReason?: string | null;
};

export type FactoryPurchaseOrderAdjustment = {
  id: string;
  sequenceNo?: number;
  kind?: "TEMPORARY_FEE" | "DELAY_PENALTY" | "OTHER" | string;
  direction?: "INCREASE" | "DECREASE" | string;
  amount?: string | number | null;
  currency?: string | null;
  description?: string | null;
  occurredAt?: string | null;
  status?: "PROVISIONAL" | "CONFIRMED" | "VOIDED" | string;
};

export type FactoryPurchaseOrderPriceCorrection = {
  id: string;
  sequenceNo?: number;
  purchaseOrderItemId?: string | null;
  batchId?: string | null;
  batchLineNo?: number | null;
  batchLineCount?: number | null;
  status?: "PENDING" | "APPROVED" | "REJECTED" | string;
  quantity?: string | number | null;
  oldUnitPrice?: string | number | null;
  newUnitPrice?: string | number | null;
  oldAmount?: string | number | null;
  newAmount?: string | number | null;
  deltaAmount?: string | number | null;
  currency?: string | null;
  reason?: string | null;
  reviewRemark?: string | null;
  sourceUnitPriceType?: string | null;
  adjustmentId?: string | null;
  settlementStatusBefore?: string | null;
  settlementStatusAfter?: string | null;
  settlementFinalPayableBefore?: string | number | null;
  settlementFinalPayableAfter?: string | number | null;
  settlementRevisionBefore?: number | null;
  settlementRevisionAfter?: number | null;
  settlementIncreaseBefore?: string | number | null;
  settlementIncreaseAfter?: string | number | null;
  settlementDecreaseBefore?: string | number | null;
  settlementDecreaseAfter?: string | number | null;
  settlementPaidBefore?: string | number | null;
  settlementPaidAfter?: string | number | null;
  settlementSettledAtBefore?: string | null;
  settlementSettledAtAfter?: string | null;
  settlementSettledByBeforeId?: string | null;
  settlementSettledByAfterId?: string | null;
  requestedAt?: string | null;
  reviewedAt?: string | null;
  requestedBy?: { id?: string; name?: string | null } | null;
  reviewedBy?: { id?: string; name?: string | null } | null;
};

export type FactoryPurchaseOrderSettlement = {
  id: string;
  revision?: number | null;
  baseAmount?: string | number | null;
  increaseAmount?: string | number | null;
  decreaseAmount?: string | number | null;
  delayDays?: number | null;
  delayPenaltyAmount?: string | number | null;
  finalPayableAmount?: string | number | null;
  currency?: string | null;
  exchangeRate?: string | number | null;
  exchangeRateDate?: string | null;
  paidAmountAtSettlement?: string | number | null;
  currentPaidAmount?: string | number | null;
  remainingAmount?: string | number | null;
  remainingRefundAmount?: string | number | null;
  status?: "PENDING_PAYMENT" | "PENDING_REFUND" | "SETTLED" | string;
  settledAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  createdBy?: { id?: string; name?: string | null } | null;
  settledBy?: { id?: string; name?: string | null } | null;
};

export type PurchaseOrderItem = {
  id?: string;
  executionItemId?: string | null;
  salesExecutionItemId?: string | null;
  productDescription?: string | null;
  productNameSnapshot?: string | null;
  specificationSnapshot?: string | null;
  descriptionSnapshot?: string | null;
  unitSnapshot?: string | null;
  allocatedQuantity?: string | number | null;
  actualDeliveredQuantity?: string | number | null;
  quantity?: string | number | null;
  purchaseUnitPrice?: string | number | null;
  supplierConfirmedUnitPrice?: string | number | null;
  effectivePurchaseUnitPrice?: string | number | null;
  unitPrice?: string | number | null;
  amount?: string | number | null;
  supplierConfirmedAmount?: string | number | null;
  effectiveAmount?: string | number | null;
  supplierPriceConfirmedAt?: string | null;
  remark?: string | null;
};

export type FactoryPurchaseOrder = {
  id: string;
  revision?: number | null;
  sequenceNo?: number | null;
  replacementForId?: string | null;
  poNo?: string | null;
  purchaseOrderNo?: string | null;
  supplierId?: string | null;
  supplier?: { id: string; supplierName?: string | null; name?: string | null } | null;
  supplierNameSnapshot?: string | null;
  purchaseCurrency?: string | null;
  currency?: string | null;
  subtotal?: string | number | null;
  effectiveSubtotal?: string | number | null;
  totalAmount?: string | number | null;
  status?: FactoryPurchaseOrderStatus | string | null;
  requestedDeliveryDate?: string | null;
  paymentTerm?: string | null;
  prepaymentRatio?: string | number | null;
  prepaymentRequiredAmount?: string | number | null;
  paidPrepaymentAmount?: string | number | null;
  prepaymentRequiredBeforeProduction?: boolean;
  deliveryQuantityToleranceRatio?: string | number | null;
  initialSupplierDeliveryDate?: string | null;
  confirmedSupplierDeliveryDate?: string | null;
  penaltyBaseAmount?: string | number | null;
  delayGraceDays?: number | null;
  delayPenaltyRatePerDay?: string | number | null;
  delayPenaltyCapRatio?: string | number | null;
  estimatedPenaltyDays?: number | null;
  estimatedPenaltyAmount?: string | number | null;
  productionStatus?: FactoryPurchaseOrderProductionStatus | string | null;
  productionStartedAt?: string | null;
  productionStartedBy?: { id?: string; name?: string | null } | null;
  productionCompletedAt?: string | null;
  productionCompletedBy?: { id?: string; name?: string | null } | null;
  productionCompletionSource?: FactoryConfirmationSource | string | null;
  productionCompletionChannel?: FactoryConfirmationChannel | string | null;
  productionCompletionContact?: string | null;
  productionCompletionRecordedAt?: string | null;
  productionCompletionRemark?: string | null;
  productionCompletionEvidenceNote?: string | null;
  productionCompletionEvidence?: string | FactoryConfirmationEvidence | null;
  productionProgress?: ProductionProgressDto;
  deliveryQuantityVariances?: DeliveryQuantityVariance[];
  actualDeliveryDate?: string | null;
  actualDeliveryRecordedAt?: string | null;
  actualDeliveryRecordedBy?: { id?: string; name?: string | null } | null;
  dispatchedAt?: string | null;
  dispatchedBy?: { id?: string; name?: string | null } | null;
  dispatchVersionNumber?: number | null;
  dispatchEmailStatus?: string | null;
  dispatchEmailSentAt?: string | null;
  dispatchEmailError?: string | null;
  dispatchSmsStatus?: string | null;
  dispatchSmsSentAt?: string | null;
  dispatchSmsError?: string | null;
  dispatchAttachment?: FactoryPurchaseOrderDispatchAttachment | null;
  supplierDeliveryDate?: string | null;
  supplierResponseRemark?: string | null;
  supplierResponseSequence?: number | null;
  supplierResponseHistory?: Array<{
    id?: string;
    sequence?: number;
    action?: string;
    deliveryDate?: string | null;
    remark?: string | null;
    source?: FactoryConfirmationSource | string | null;
    channel?: FactoryConfirmationChannel | string | null;
    supplierContact?: string | null;
    supplierRespondedAt?: string | null;
    evidenceNote?: string | null;
    evidence?: string | FactoryConfirmationEvidence | null;
    priceChanges?: Array<{
      purchaseOrderItemId?: string;
      unitPrice?: string | number | null;
      amount?: string | number | null;
    }>;
    recordedAt?: string | null;
    recordedBy?: { id?: string; name?: string | null } | null;
    respondedAt?: string | null;
    internalDecision?: string | null;
    internalDecisionRemark?: string | null;
    internalDecidedAt?: string | null;
    internalDecidedBy?: { id?: string; name?: string | null } | null;
  }>;
  confirmationEvents?: FactoryPurchaseOrderConfirmationEvent[];
  respondedAt?: string | null;
  respondedBy?: { id?: string; name?: string | null } | null;
  payments?: FactoryPurchaseOrderPayment[];
  adjustments?: FactoryPurchaseOrderAdjustment[];
  priceCorrections?: FactoryPurchaseOrderPriceCorrection[];
  settlement?: FactoryPurchaseOrderSettlement | null;
  remark?: string | null;
  items?: PurchaseOrderItem[];
};
import type { ProductionProgressDto } from "../../../lib/platform/factory-purchase-order-production-progress-values";
import type { DeliveryQuantityVariance } from "../delivery-quantity-variance";
