const { request } = require("../../utils/api");
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function value(value) { if (value === null || value === undefined || value === "") return "-"; if (Array.isArray(value)) return value.map((x) => typeof x === "object" ? (x.label || x.fileName || x.name || "") : x).filter(Boolean).join("、") || "-"; if (typeof value === "object") return value.label || value.name || "-"; if (typeof value === "boolean") return value ? "是" : "否"; return String(value).replace("T", " ").replace(/\.000Z$/, ""); }
function linesOf(row) { if (!row || typeof row !== "object") return []; const hidden = new Set(["id", "orderId", "customerId", "supplierId", "items", "documents", "records", "timeline", "alerts", "availableFiles", "draft", "customer", "order"]); return Object.keys(row).filter((key) => !hidden.has(key) && row[key] !== undefined && row[key] !== null && typeof row[key] !== "object").slice(0, 18).map((key) => ({ label: key, value: value(row[key]) })); }
Page({
  data: { key: "", id: "", orderId: "", loading: true, acting: false, error: "", notice: "", detail: null, lines: [], recipientEmails: "", ccEmails: "", emailSubject: "", emailBody: "", emailLanguage: "EN", manualRemark: "", paymentDate: today() },
  onLoad(options) { this.setData({ key: options.key || "", id: options.id || "", orderId: options.orderId || options.id || "" }); const titles = { costs: "成本详情", customerCommunication: "客户沟通详情", oceanControlTower: "运输跟踪详情", logisticsFees: "物流费用操作", taxRefund: "退税资料详情" }; wx.setNavigationBarTitle({ title: titles[this.data.key] || "业务详情" }); this.load(); },
  async load() { this.setData({ loading: true, error: "" }); try { let result, detail; if (this.data.key === "costs") { result = await request({ url: `/api/costs/${encodeURIComponent(this.data.id)}` }); detail = result.cost || (result.data && result.data.cost); } else if (this.data.key === "customerCommunication") { result = await request({ url: `/api/customer-communications/${encodeURIComponent(this.data.orderId)}` }); detail = result.detail || result; } else if (this.data.key === "oceanControlTower") { result = await request({ url: `/api/freightower/ocean-trackings/${encodeURIComponent(this.data.id)}` }); detail = result.tracking || result.data || result; } else if (this.data.key === "taxRefund") { result = await request({ url: `/api/tax-refunds/${encodeURIComponent(this.data.orderId)}` }); detail = result.order || result.data; } else { result = await request({ url: "/api/logistics-costs?page=1&pageSize=200" }); const rows = result.rows || (result.data && result.data.rows) || []; detail = rows.find((x) => x.id === this.data.id) || { id: this.data.id }; } const patch = { detail, lines: linesOf(detail) }; if (this.data.key === "customerCommunication") { const draft = detail.draft || {}; Object.assign(patch, { recipientEmails: (draft.recipientEmails || []).join(", "), ccEmails: (draft.ccEmails || []).join(", "), emailSubject: draft.subject || "", emailBody: draft.body || "", emailLanguage: draft.language || "EN" }); } this.setData(patch); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  input(e) { this.setData({ [e.currentTarget.dataset.field]: e.detail.value }); },
  async run(url, method, data, successMessage, timeout = 30000) { if (this.data.acting) return; this.setData({ acting: true, error: "", notice: "" }); try { const result = await request({ url, method, data, timeout }); this.setData({ notice: result.message || successMessage }); wx.showToast({ title: successMessage, icon: "success" }); await this.load(); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ acting: false }); } },
  sendCommunication() { const d = this.data; if (!d.recipientEmails.trim() || !d.emailSubject.trim() || !d.emailBody.trim()) return this.setData({ error: "请完整填写收件人、标题和正文" }); wx.showModal({ title: "发送清关资料", content: "将向客户发送邮件和当前可用清关附件，是否继续？", success: (r) => { if (r.confirm) this.run(`/api/customer-communications/${encodeURIComponent(d.orderId)}`, "PATCH", { action: "sendCustomsClearanceDocs", recipientEmails: d.recipientEmails, ccEmails: d.ccEmails, emailLanguage: d.emailLanguage, emailSubject: d.emailSubject, emailBody: d.emailBody }, "清关资料已发送", 65000); } }); },
  markSent() { this.run(`/api/customer-communications/${encodeURIComponent(this.data.orderId)}/mark-sent`, "POST", { deliveryMethod: "小程序线下登记", sentAt: new Date().toISOString(), remark: this.data.manualRemark }, "已标记发送"); },
  unmarkSent() { this.run(`/api/customer-communications/${encodeURIComponent(this.data.orderId)}/unmark-sent`, "POST", {}, "已取消标记"); },
  syncOcean() { this.run(`/api/freightower/ocean-trackings/${encodeURIComponent(this.data.id)}/sync`, "POST", {}, "运输节点已同步", 300000); },
  markCostPaid() { this.run(`/api/costs/${encodeURIComponent(this.data.id)}/payment`, "PATCH", { paid: true, paidAt: this.data.paymentDate }, "已标记付款"); },
  cancelCostPaid() { this.run(`/api/costs/${encodeURIComponent(this.data.id)}/payment`, "PATCH", { paid: false, paidAt: null }, "已取消付款状态"); },
  voidCost() { wx.showModal({ title: "作废成本", editable: true, placeholderText: "请输入作废原因", confirmColor: "#b3332b", success: (r) => { if (r.confirm && r.content.trim()) this.run(`/api/costs/${encodeURIComponent(this.data.id)}`, "DELETE", { reason: r.content.trim() }, "成本已作废"); } }); },
  logisticsAction(e) { const action = e.currentTarget.dataset.action, labels = { submitBill: "提交审核", approve: "审核通过", reject: "驳回", markPaid: "标记已付款", reversePayment: "冲销付款", withdraw: "撤回草稿", voidBill: "作废账单" }; const needsReason = ["reject", "reversePayment", "voidBill"].includes(action); wx.showModal({ title: labels[action], content: needsReason ? "请输入原因后继续。" : `确认执行“${labels[action]}”？`, editable: needsReason, placeholderText: "请输入原因", confirmColor: ["reject", "reversePayment", "voidBill"].includes(action) ? "#b3332b" : "#176c4e", success: (r) => { if (!r.confirm || (needsReason && !r.content.trim())) return; const data = { action, ...(action === "reject" ? { rejectReason: r.content.trim() } : {}), ...(["reversePayment", "voidBill"].includes(action) ? { reason: r.content.trim() } : {}), ...(action === "markPaid" ? { paymentStatus: "已付款", paymentDate: this.data.paymentDate } : {}) }; this.run(`/api/logistics-costs/${encodeURIComponent(this.data.id)}`, "PATCH", data, labels[action], 65000); } }); },
  refreshTax() { this.run(`/api/tax-refunds/${encodeURIComponent(this.data.orderId)}`, "PATCH", { action: "refreshCompleteness" }, "完整度已刷新", 65000); },
  submitTax() { wx.showModal({ title: "提交并归档退税资料", content: "后端将再次校验全部必需资料和状态，是否继续？", success: (r) => { if (r.confirm) this.run(`/api/tax-refunds/${encodeURIComponent(this.data.orderId)}`, "PATCH", { status: "SUBMITTED" }, "退税资料已提交", 65000); } }); },
  cancelTax() { this.run(`/api/tax-refunds/${encodeURIComponent(this.data.orderId)}`, "PATCH", { cancelArchive: true, status: "NOT_READY" }, "退税归档已取消", 65000); },
});
