const { request } = require("../../utils/api");
const CURRENCIES = ["CNY", "USD", "EUR", "GBP", "HKD"], TERMS = ["EXW", "FOB", "FCA", "CFR", "CIF", "DDP", "DAP", "其他"], PAYMENTS = ["见提单复印件付款", "OA账期", "到港后付款", "其他付款约定"], PAYMENT_VALUES = ["COPY_BL", "OA", "AFTER_ARRIVAL", "CUSTOM"];
Page({
  data: { loading: true, saving: false, error: "", customers: [], customerNames: [], customerIndex: -1, entities: [], entityNames: [], entityIndex: -1, suppliers: [], supplierNames: [], supplierIndex: -1, currencies: CURRENCIES, currencyIndex: 0, terms: TERMS, termIndex: 0, payments: PAYMENTS, paymentIndex: 0, form: { customerId: "", orderNo: "", currency: "CNY", exchangeRate: "1", estimatedReceivableAmount: "", finalReceivableAmount: "", tradeTerm: "EXW", paymentTermType: "COPY_BL", paymentTerm: "", dueDate: "", creditDays: "30", reminderDays: "7", status: "草稿", businessEntityId: "", logisticsSupplierIds: [], remark: "" } },
  onLoad() { this.load(); }, async load() { try { const [c, e, s] = await Promise.all([request({ url: "/api/customers" }), request({ url: "/api/business-entities" }), request({ url: "/api/suppliers/available" })]); const customers = c.customers || [], entities = (e.entities || []).filter((x) => x.status !== "停用"), suppliers = (s.suppliers || []).filter((x) => ["物流供应商", "报关供应商", "海运供应商", "港杂费用供应商"].includes(x.supplierType)), entityIndex = entities.length ? Math.max(0, entities.findIndex((x) => x.isDefault)) : -1; this.setData({ customers, customerNames: customers.map((x) => x.displayName || x.shortName || x.name), entities, entityNames: entities.map((x) => x.displayName || x.shortName || x.name), entityIndex, "form.businessEntityId": entities[entityIndex] && entities[entityIndex].id || "", suppliers, supplierNames: suppliers.map((x) => `${x.supplierName || x.name} · ${x.supplierType}`) }); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ loading: false }); } },
  chooseCustomer(e) { const customerIndex = Number(e.detail.value), x = this.data.customers[customerIndex], currency = x.defaultCurrency || "CNY"; this.setData({ customerIndex, "form.customerId": x.id, "form.currency": currency, currencyIndex: Math.max(0, CURRENCIES.indexOf(currency)), "form.exchangeRate": currency === "CNY" ? "1" : "" }); }, chooseEntity(e) { const entityIndex = Number(e.detail.value); this.setData({ entityIndex, "form.businessEntityId": this.data.entities[entityIndex].id }); }, chooseCurrency(e) { const currencyIndex = Number(e.detail.value), currency = CURRENCIES[currencyIndex]; this.setData({ currencyIndex, "form.currency": currency, "form.exchangeRate": currency === "CNY" ? "1" : "" }); }, chooseTerm(e) { const termIndex = Number(e.detail.value), term = TERMS[termIndex]; this.setData({ termIndex, "form.tradeTerm": term, ...(term === "EXW" ? { supplierIndex: -1, "form.logisticsSupplierIds": [] } : {}) }); }, choosePayment(e) { const paymentIndex = Number(e.detail.value); this.setData({ paymentIndex, "form.paymentTermType": PAYMENT_VALUES[paymentIndex] }); }, chooseSupplier(e) { const supplierIndex = Number(e.detail.value); this.setData({ supplierIndex, "form.logisticsSupplierIds": [this.data.suppliers[supplierIndex].id] }); }, onInput(e) { this.setData({ [`form.${e.currentTarget.dataset.field}`]: e.detail.value }); },
  validate() { const f = this.data.form; if (!f.customerId) return "请选择客户"; if (!f.orderNo.trim()) return "请填写订单号"; if (!f.businessEntityId) return "请选择业务主体"; if (!(Number(f.exchangeRate) > 0)) return "请填写有效汇率"; if (!(Number(f.estimatedReceivableAmount) >= 0)) return "请填写预计应收金额"; if (f.tradeTerm !== "EXW" && !f.logisticsSupplierIds.length) return "非 EXW 订单请选择物流供应商"; if (f.paymentTermType === "CUSTOM" && !f.paymentTerm.trim()) return "请填写其他付款约定"; return ""; },
  async submit() { if (this.data.saving) return; const message = this.validate(); if (message) return this.setData({ error: message }); this.setData({ saving: true, error: "" }); try { const f = this.data.form; const result = await request({ url: "/api/orders", method: "POST", data: { ...f, orderNo: f.orderNo.trim(), exchangeRate: Number(f.exchangeRate), estimatedReceivableAmount: Number(f.estimatedReceivableAmount), finalReceivableAmount: f.finalReceivableAmount ? Number(f.finalReceivableAmount) : undefined, paymentTerm: f.paymentTermType === "CUSTOM" ? f.paymentTerm.trim() : undefined, creditDays: ["OA", "AFTER_ARRIVAL"].includes(f.paymentTermType) ? Number(f.creditDays || 0) : undefined, reminderDays: Number(f.reminderDays || 7), remark: f.remark.trim() } }); wx.showToast({ title: result.message || "订单已保存", icon: "success" }); setTimeout(() => wx.navigateBack(), 600); } catch (error) { this.setData({ error: error.message }); } finally { this.setData({ saving: false }); } },
});
